### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_10_vanweather#52]
Major:
- [x] Update text in cards dynamically to say how many year and the values for that time period
- [x] Be able to show more data by using vegafusion
- [x] Update data over time each time it is refreshed
- [x] Some separation to indicate which widgets are global and which are local. Pretty much only that the first row is only controlled by the date picker, which is not intuitive currently.

Minor:
- [x] Points and line same color?
- [x] Dropdown font is small
- [x] Slightly smaller so no scrolling needed
- [x] Padding withing cards?
- [x] Maybe smooth
- [x] Center title? Padding under? Bg color

**Comment by sivakornchong** [comment]
Update comments for milestone 3
Major:
1. Cards' text have been set to be dynamic with values and number of days updated.
2. Added vegafusion into all the relevant cards.
3. Set up additional refresh-button with automated data pipeline, allowing for users to fetch latest data up until today/ latest availability via openMateo API.
4. Now, all the widgets do not need to be seperated as all cards and charts are dynamically updated to the date range. 

Minor:
1. We have chosen to remove the blue points instead. 
2. To be fixed in milestone 4
3. Done
4. Done
5. We have chosen that we want to highlight extreme values in the top right chart, and would keep the chart as it is. 
6. These artisitc consideration would be made in milestone 4.

**Comment by czwcandy** [comment]
Thank you for your feedback. We updated our dashboard accordingly, some were finished in Milestone3, others were all finished this week.
