### ISSUE TITLE
Feedback from JohnShiu

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_10_vanweather#55]
- [ ] **A bigger picture comment**: The target audience of your dashboard is the stakeholders who want to understand the evolving climate landscape and able to take actions to address and adapt that. I think you could consider putting more focus on those who can take significant actions, e.g. politician. You won't need to change anything in your README writings. However, having that focus in mind, you can adjust your dashboard, e.g. make one of the plots significantly bigger and draw their first attention to that plot, to "unconsciously" inject a message into those influential audience. 
 
 - [x] The title is still "Dash". You may consider adding your title "VanWeather" in your `Dash(..., title="VanWeather")`
   - <img width="541" alt="Screenshot 2024-04-11 at 4 58 17 PM" src="https://github.com/UBC-MDS/DSCI-532_2024_10_vanweather/assets/26508851/108fed7b-c522-4787-b1fa-bf55ef5aaf3a">

 - [x] When the aggregation is yearly especially, the blue points on the altair charts can be larger, so that it's easier to tooltip

 - [x] Can the value in the blocks (on topleft) change according to the selected date range, instead of fixing it to the past 10 years?

 - [ ] The title is either too long, or you may use a top bar to hold it (you may check some examples in lecture 6)

Other than these, the dashboard is nice, and appreciate your effort in making the world better!

Best,
John

**Comment by sivakornchong** [comment]
the ticked items have been resolved in Milestone3.

Other items:
The title is either too long, or you may use a top bar to hold it (you may check some examples in lecture 6)
- We will not implement this as it will take too much of a revamp to our current setup.

 A bigger picture comment: The target audience of your dashboard is the stakeholders who want to understand the evolving climate landscape and able to take actions to address and adapt that. I think you could consider putting more focus on those who can take significant actions, e.g. politician. You won't need to change anything in your README writings. However, having that focus in mind, you can adjust your dashboard, e.g. make one of the plots significantly bigger and draw their first attention to that plot, to "unconsciously" inject a message into those influential audience.
- This would require a big change in layout, which is different from what we envisioned since the start.

**Comment by czwcandy** [comment]
We updated our dashboard based on some feedbacks . For others, we don't plan to update after discussion according to reasons Oak commented.
