### ISSUE TITLE
Feedback from Sophia (Tianhong) Zhao

### ISSUE THREAD

**Issue by zth96** [UBC-MDS/DSCI-532_2024_10_vanweather#63]
Well done Group 10! There are only some minor improvements to be made to make this dash perfect. 

###  Larger Points of Feedback

1. The application aligns well with the intended usage scenario and stakeholder audience. 

2. Upon initially interacting with the dashboard, I experienced some confusion with the data range selection. A clearer distinction between the start and end dates would be helpful. For instance, the absence of a line indicator led me to believe I could click anywhere to select a range, yet I found myself selecting only an end date on my first attempt. Furthermore, when using the 'Year' option under 'Aggregation for charts', I encountered empty charts due to an insufficiently large date range. It was not immediately apparent that dates could be manually entered as the calendar interface suggested otherwise. A tooltip explaining the functionality or a reevaluation of the date range selector's design could improve usability. Additionally, enhancing the legibility of the Temperature variable dropdown and darkening the graph titles would improve clarity and visibility.

3. The use of line charts effectively conveys trends in the data. It’s great to see multiple plots, but users could benefit from a consolidated view or summary statistics that give a snapshot of the weather patterns.

4. For certain stakeholders, terms like 'apparent temperature' and 'sum of shortwave radiation' might be confusing. A glossary or explanatory tooltips within the dashboard, or simplifying the language used to describe these terms, could aid comprehension.

### Smaller Points of Feedback

1. The text within dropdown menu options is quite small and could benefit from being enlarged for better readability.

2. The proximity of the five charts to one another may compromise focus. Increasing the spacing between each chart could alleviate this visual congestion.

3. On a laptop, I had to scroll to see all the charts, which prevented simultaneous comparison. Resizing the charts to fit within a single screen without the need for scrolling would enhance the user experience.

4. The widgets function correctly, but the text within the Temperature variable dropdown is lengthy, causing overlap with the 'remove' icon. Resizing the widgets or adjusting the text size could prevent this overlap.

5. The README and proposal are straightforward, and the GIF is a useful visual aid. However, relying solely on the GIF may not suffice for all users. Adding simple written instructions that describe each widget's functionality, contents, and impact on the charts could provide clear, accessible guidance.

**Comment by sivakornchong** [comment]
Larger Points of Feedback
The application aligns well with the intended usage scenario and stakeholder audience.

Upon initially interacting with the dashboard, I experienced some confusion with the data range selection. A clearer distinction between the start and end dates would be helpful. For instance, the absence of a line indicator led me to believe I could click anywhere to select a range, yet I found myself selecting only an end date on my first attempt. Furthermore, when using the 'Year' option under 'Aggregation for charts', I encountered empty charts due to an insufficiently large date range. It was not immediately apparent that dates could be manually entered as the calendar interface suggested otherwise. A tooltip explaining the functionality or a reevaluation of the date range selector's design could improve usability. Additionally, enhancing the legibility of the Temperature variable dropdown and darkening the graph titles would improve clarity and visibility.

- We will write a note on the dashboard that you can key in the date manually.

The use of line charts effectively conveys trends in the data. It’s great to see multiple plots, but users could benefit from a consolidated view or summary statistics that give a snapshot of the weather patterns.
- We have the KPIs as summary statistics. 

For certain stakeholders, terms like 'apparent temperature' and 'sum of shortwave radiation' might be confusing. A glossary or explanatory tooltips within the dashboard, or simplifying the language used to describe these terms, could aid comprehension.
- We will add a link in the dashboard to a README file containing variable explanations. 

Smaller Points of Feedback
The text within dropdown menu options is quite small and could benefit from being enlarged for better readability.
- If it is bigger, it will be overlapping. 

The proximity of the five charts to one another may compromise focus. Increasing the spacing between each chart could alleviate this visual congestion.
- We will defer to Joel's feedback, which is contradictory. 

On a laptop, I had to scroll to see all the charts, which prevented simultaneous comparison. Resizing the charts to fit within a single screen without the need for scrolling would enhance the user experience.
- We resolved this as per Joel's feedback. 

The widgets function correctly, but the text within the Temperature variable dropdown is lengthy, causing overlap with the 'remove' icon. Resizing the widgets or adjusting the text size could prevent this overlap.
- There is no more remove icon. 

The README and proposal are straightforward, and the GIF is a useful visual aid. However, relying solely on the GIF may not suffice for all users. Adding simple written instructions that describe each widget's functionality, contents, and impact on the charts could provide clear, accessible guidance.
- Yes, this will be incorperated in the README file.

**Comment by czwcandy** [comment]
We updated our dashboard based on some feedbacks . For others, we don't plan to update after discussion according to reasons Oak commented.
