### ISSUE TITLE
Feedback from Chris Gao 

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/DSCI-532_2024_10_vanweather#73]
Thank you for presenting this time-series dashboard! To be honest this looks great, but provided below are some suggestions that might help you to make it even better. 

Bigger Picture Issue

- The dashboard is not the easiest to understand by the first glance. There could be more sufficient information in the README so that I could get holistic information about the general metrics in the dashboard. Currently in the README file only exists a short introduction, without mentioning the metrics in the interest and how they come into the play

More Important Feedback
-  It is good that you have implemented a various of filtering methods on the left side of the dashboard, but it could be more intuitive if you could include a short explanation in the README file on the general implications of the filters. For a person without any domain knowledge, it can be confusing in terms of the filter’s meaning. 
- For Date Range toggle, it could be tedious in terms of selecting data range in a larger frame, I.e. 2014-2016. This needs a lot more clicking and could be avoided by the option of simply type the input of start date and end date in addition to what you currently have. The calendar visualization is an excellent visual cue in terms of months, week, and days, years not so much.

More Minor Adjustment
- The title for the chart can be bigger. Since we have 5 line charts, a more astute title can help the audience to differentiate them. 
- The boxes for the summarizing statistics can be larger. We see that some statistics are on the line of boxes. 

Overall, I find the dashboard very helpful to understand the data and fun to play with. Thank you for the awesomework!

**Comment by sivakornchong** [comment]
Issue review by team:

Issue taken and will be implemented

The dashboard is not the easiest to understand by the first glance. There could be more sufficient information in the README so that I could get holistic information about the general metrics in the dashboard. Currently in the README file only exists a short introduction, without mentioning the metrics in the interest and how they come into the play
It is good that you have implemented a various of filtering methods on the left side of the dashboard, but it could be more intuitive if you could include a short explanation in the README file on the general implications of the filters. For a person without any domain knowledge, it can be confusing in terms of the filter’s meaning.

- > we take this feedback and will proceed to clarify the metrics in README
- > we will also highlight the users for our dashboard

The boxes for the summarizing statistics can be larger. We see that some statistics are on the line of boxes.
-> We will take a look at how to implement the changes to the boxes.

Thank you for these comments, while we would like to address all the concerns. We do not think the comments on (title/ date range) are of significant concerns. Date can still be keyed into the boxes via typing. Titles have correct sizes in our opinion.

**Comment by czwcandy** [comment]
We updated our dashboard based on some feedbacks . For others, we don't plan to update after discussion according to reasons Oak commented.
